### ISSUE TITLE
URL constructor implementation is incomplete

### ISSUE THREAD

**Issue by stefanlucas** [BabylonJS/JsRuntimeHost#13]
**Describe the bug**
URL constructor is partially implemented, it only supports one argument and the url parsing is limited. We should move the parsing to UrlLib and use platform specific functions to parse the URL and get the parts. 

**Expected behavior**
Same behavior as the [javascript URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) constructor 

**Other**
 - Platform: Win32, Android, iOS

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
