### ISSUE TITLE
URLSearchParams constructor implementation is incomplete

### ISSUE THREAD

**Issue by stefanlucas** [BabylonJS/JsRuntimeHost#14]
**Describe the bug**
URLSearchParams constructor is partially implemented, it does not support sequence of pairs and records. eg:
```
const params1 = new URLSearchParams([["foo", "1"], ["bar", "2"]]); (sequence of pairs)
const params2 = new URLSearchParams({ "foo": "1", "bar": "2" }); (records)
```

**Expected behavior**
Same behavior as the [javascript URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) constructor

**Other**
 - Platform: Win32, Android, iOS

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
