### ISSUE TITLE
V8 inspector shutdown crash

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/JsRuntimeHost#47]
C++ Check added with this PR : https://github.com/BabylonJS/BabylonNative/pull/1277
to shutdown and restart. At 1st shutdown, there is a crash due to V8 inspector not being properly stopped.

**Comment by bghgary** [comment]
Maybe related: https://github.com/BabylonJS/JsRuntimeHost/issues/21

**Comment by CedricGuillemet** [comment]
> #21

Yes, it looks like the same one

**Comment by thomlucc** [comment]
fixed
