### ISSUE TITLE
V8 profiling

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/JsRuntimeHost#77]
Following update on node-api, profile V8 to check for performance regression, in particular the use of private_key.
Spheres test in UnitTests can be a start.

I think more CPP tests that test a specific part of JSEngine<->CPP communication layer is the way to go.
From what I've seen so far, still with UnitTests, is most time taken by bgfx.

**Comment by bghgary** [comment]
I pushed a fix in the PR to fix the regression. I can't remember how I determined this was the slow down, so it would be great to figure out how to figure this out. 😄
